export const CURRENT_USER_STATE_CHANGE = 'CURRENT_USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'
export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'

export const FETCH_POSTS = 'FETCH_POSTS'
export const INCREMENT_INDEX = 'INCREMENT_INDEX'
